application: whispers-of-abaddon
version: qa
runtime: python27
threadsafe: yes
api_version: 1

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^view/.*$

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: django
  version: latest

handlers:

- url: /static
  static_dir: frontend/static

- url: /system/.*
  script: admin.application
  login: admin
  secure: always

- url: /admin/.*
  script: admin.application
  login: required
  secure: always

- url: /(login|user|account).*
  script: whoa.application
  secure: always

- url: /.*
  script: whoa.application
  secure: never
