application: whispers-of-abaddon
version: qa
runtime: python27
threadsafe: yes
api_version: 1

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^view/.*$

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: django
  version: latest

handlers:
- url: /images
  static_dir: static/images

- url: /scripts
  static_dir: static/scripts

- url: /fonts
  static_dir: static/fonts

- url: /files
  static_dir: static/files

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /system/.*
  script: admin.application
  login: admin
  secure: always

- url: /admin/docs
  static_dir: docs/build/html
  login: required

- url: /admin/.*
  script: admin.application
  login: required
  secure: always

- url: /(login|user|account).*
  script: whoa.app
  secure: always

- url: /.*
  script: whoa.app
  secure: never
